# Generated by Django 5.2.17 on 2026-09-30 07:11

import apps.bookings.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinemas', '0001_initial'),
        ('showtimes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=apps.bookings.models.generate_booking_code, editable=False, max_length=12, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('confirmed', 'Đã xác nhận'), ('expired', 'Hết hạn giữ ghế'), ('cancelled', 'Đã hủy')], default='pending', max_length=20)),
                ('total_amount', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='showtimes.showtime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookings.booking')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cinemas.seat')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='showtimes.showtime')),
            ],
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'expires_at'], name='bookings_bo_status_86acff_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', '-created_at'], name='bookings_bo_user_id_6151bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user', 'showtime'), name='one_pending_booking_per_user_showtime'),
        ),
        migrations.AddConstraint(
            model_name='bookingseat',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('showtime', 'seat'), name='uniq_active_seat_per_showtime'),
        ),
        migrations.AddConstraint(
            model_name='bookingseat',
            constraint=models.UniqueConstraint(fields=('booking', 'seat'), name='uniq_seat_per_booking'),
        ),
    ]
