# Generated by Django 5.2.17 on 2026-10-01 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_checked_in_at_booking_checked_in_by_and_more'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='promotions.voucher'),
        ),
        migrations.CreateModel(
            name='BookingCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('unit_price', models.PositiveIntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_lines', to='bookings.booking')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='promotions.combo')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('booking', 'combo'), name='uniq_combo_per_booking'), models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='booking_combo_quantity_positive')],
            },
        ),
    ]
