"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import environ
from pathlib import Path
from datetime import timedelta
from celery.schedules import crontab
import sys
from django.core.exceptions import ImproperlyConfigured

env = environ.Env(DJANGO_DEBUG=(bool, False))

TESTING = "test" in sys.argv  # đang chạy `manage.py test ...`

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DJANGO_DEBUG")

ALLOWED_HOSTS = ["*"] if DEBUG else env.list("ALLOWED_HOSTS", default=[])

if (
    not DEBUG
    and not TESTING
    and (len(SECRET_KEY) < 50 or SECRET_KEY.startswith(("django-insecure", "dev-")))
):
    # Fail-fast: lỗi cấu hình phải nổ lúc khởi động, không phải lúc đang chạy thật
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY quá yếu cho production (cần >= 50 ký tự, không phải key mẫu)."
    )

ENABLE_API_DOCS = env.bool(
    "ENABLE_API_DOCS", default=DEBUG
)  # Swagger/schema chỉ bật ở dev

# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.postgres",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "corsheaders",
    "django_filters",
    "apps.users",
    "apps.movies",
    "apps.cinemas",
    "apps.showtimes",
    "apps.bookings",
    "apps.payments",
    "apps.reports",
    "apps.promotions",
    "apps.core",
]

MIDDLEWARE = [
    "apps.core.middleware.RequestContextMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {"default": env.db("DATABASE_URL")}
DATABASES["default"]["CONN_MAX_AGE"] = env.int("DB_CONN_MAX_AGE", default=0)  # prod: 60
DATABASES["default"][
    "CONN_HEALTH_CHECKS"
] = True  # kiểm tra kết nối cũ còn sống trước khi dùng lại
DATABASES["default"].setdefault("OPTIONS", {})["connect_timeout"] = 5

# Redis dùng 3 "ngăn": 0 = giữ ghế + channel layer, 1 = Celery broker, 2 = cache (throttling)
if TESTING:
    CACHES = {"default": {"BACKEND": "django.core.cache.backends.locmem.LocMemCache"}}
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": env("CACHE_URL", default="redis://redis:6379/2"),
            "KEY_PREFIX": "cinema",
            # Không có timeout thì Redis treo sẽ làm TỪNG request treo theo
            "OPTIONS": {"socket_connect_timeout": 1, "socket_timeout": 1},
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "vi"

TIME_ZONE = "Asia/Ho_Chi_Minh"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "users.User"

AUTHENTICATION_BACKENDS = [
    "apps.users.backends.EmailOrUsernameBackend",
    "django.contrib.auth.backends.ModelBackend",
]

NUM_PROXIES = env.int("NUM_PROXIES", default=0)

THROTTLE_RATES = {
    "anon": "240/min",
    "user": "600/min",
    "login": "10/min",
    "register": "5/hour",
    "voucher": "20/min",
    "hold": "30/min",
    "pay": "10/min",
    "checkin": "120/min",
}
if TESTING:
    # Test gửi rất nhiều request từ cùng một "IP": nới cực cao, riêng test throttling tự hạ từng scope
    THROTTLE_RATES = {scope: "1000000/min" for scope in THROTTLE_RATES}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    # Secure by default: endpoint nào công khai phải khai báo AllowAny rõ ràng
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 12,
    "DEFAULT_THROTTLE_CLASSES": (
        "apps.core.throttling.AnonThrottle",
        "apps.core.throttling.UserThrottle",
        "apps.core.throttling.ScopedThrottle",
    ),
    "DEFAULT_THROTTLE_RATES": THROTTLE_RATES,
    "NUM_PROXIES": NUM_PROXIES,
    "EXCEPTION_HANDLER": "apps.core.exceptions.api_exception_handler",
}
if not DEBUG:
    # Production chỉ trả JSON: không có giao diện Browsable API
    REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"] = (
        "rest_framework.renderers.JSONRenderer",
    )

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Cinema Booking API",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

CORS_ALLOWED_ORIGINS = env.list(
    "CORS_ALLOWED_ORIGINS", default=["http://localhost:5173"]
)

REDIS_URL = env("REDIS_URL")
SEAT_HOLD_SECONDS = env.int("SEAT_HOLD_SECONDS", default=600)  # 10 phút
MAX_SEATS_PER_BOOKING = env.int("MAX_SEATS_PER_BOOKING", default=8)

ASGI_APPLICATION = "config.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [REDIS_URL]},
    }
}

# --- Celery ---
CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="redis://redis:6379/1")
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_TIMEZONE = TIME_ZONE  # crontab hiểu theo giờ Việt Nam
CELERY_TASK_IGNORE_RESULT = True  # không cần result backend
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_SOFT_TIME_LIMIT = 45
CELERY_TASK_TIME_LIMIT = 60

CELERY_BEAT_SCHEDULE = {
    "expire-pending-bookings": {
        "task": "bookings.expire_pending",
        "schedule": 10.0,  # mỗi 10 giây
        "options": {"expires": 10},  # task cũ hơn 10 giây thì bỏ qua
    },
    "flush-expired-jwt-tokens": {
        "task": "users.flush_expired_tokens",
        "schedule": crontab(hour=3, minute=0),  # 3h sáng mỗi ngày
    },
    "reconcile-pending-payments": {
        "task": "payments.reconcile_pending",
        "schedule": 60.0,
        "options": {"expires": 60},
    },
}

# --- Email (dev: Mailpit hứng thư, không gửi ra ngoài) ---
EMAIL_BACKEND = env(
    "EMAIL_BACKEND", default="django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_HOST = env("EMAIL_HOST", default="mailpit")
EMAIL_PORT = env.int("EMAIL_PORT", default=1025)
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="Cinema Booking admin@gmail.com")

# --- Payments ---
PAYMENT_WEBHOOK_SECRET = env("PAYMENT_WEBHOOK_SECRET")
PAYMENT_MOCK_ENABLED = env.bool(
    "PAYMENT_MOCK_ENABLED", default=DEBUG
)  # chỉ bật khi dev
PAYMENT_MIN_SECONDS_TO_PAY = (
    60  # đơn còn dưới ngần này thì không cho bắt đầu thanh toán
)
PAYMENT_PROVIDER = env("PAYMENT_PROVIDER", default="mock")
VNPAY_TMN_CODE = env("VNPAY_TMN_CODE", default="")
VNPAY_HASH_SECRET = env("VNPAY_HASH_SECRET", default="")
VNPAY_PAY_URL = env(
    "VNPAY_PAY_URL",
    default="https://sandbox.vnpayment.vn/paymentv2/vpcpay.html",
)
VNPAY_QUERY_URL = env(
    "VNPAY_QUERY_URL",
    default="https://sandbox.vnpayment.vn/merchant_webapi/api/transaction",
)
VNPAY_RETURN_URL = env("VNPAY_RETURN_URL", default="http://localhost:5173")
PAYMENT_IPN_IP_ALLOWLIST = env.list("PAYMENT_IPN_IP_ALLOWLIST", default=[])
PAYMENT_RECONCILE_AFTER_SECONDS = env.int("PAYMENT_RECONCILE_AFTER_SECONDS", default=120)

# --- Check-in ---
CHECKIN_OPENS_BEFORE_MINUTES = env.int("CHECKIN_OPENS_BEFORE_MINUTES", default=60)

# --- Promotions ---
MIN_PAYABLE_AMOUNT = env.int(
    "MIN_PAYABLE_AMOUNT", default=1000
)  # đơn không bao giờ rẻ hơn mức này

# --- Bảo mật ---
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
SECURE_REFERRER_POLICY = "same-origin"
CSRF_TRUSTED_ORIGINS = env.list(
    "CSRF_TRUSTED_ORIGINS", default=[]
)  # Django Admin qua HTTPS cần

if not DEBUG:
    # Django nằm sau Nginx (nơi kết thúc TLS). CHỈ an toàn khi Nginx luôn GHI ĐÈ header này
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # HSTS không rút lại được: bắt đầu 3600, ổn rồi mới tăng dần lên 1 năm
    SECURE_HSTS_SECONDS = env.int("HSTS_SECONDS", default=0)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool("HSTS_INCLUDE_SUBDOMAINS", default=False)
    # Chuyển hướng HTTP->HTTPS do Nginx làm (health check nội bộ đi bằng HTTP, Django mà chuyển hướng là hỏng)
    SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=False)
    if not SECURE_SSL_REDIRECT:
        SILENCED_SYSTEM_CHECKS = ["security.W008"]

LOG_LEVEL = env("LOG_LEVEL", default="WARNING" if TESTING else "INFO")
LOG_FORMAT = env("LOG_FORMAT", default="text" if DEBUG else "json")   # "text" | "json"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {"request_id": {"()": "apps.core.logs.RequestIdFilter"}},
    "formatters": {
        "text": {"format": "%(asctime)s %(levelname)-7s [%(request_id)s] %(name)s: %(message)s"},
        "json": {"()": "apps.core.logs.JsonFormatter"},
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "stream": "ext://sys.stdout",
            "filters": ["request_id"],   # gắn ở HANDLER để bắt được record từ mọi logger
            "formatter": LOG_FORMAT,
        },
        "null": {"class": "logging.NullHandler"},
    },
    "root": {"handlers": ["console"], "level": "WARNING"},
    "loggers": {
        "apps": {"level": LOG_LEVEL},
        "django": {"handlers": ["console"], "level": "INFO", "propagate": False},
        "django.request": {"level": "ERROR"},   # 4xx đã có trong access log
        "django.security.DisallowedHost": {"handlers": ["null"], "propagate": False},
    },
}

SENTRY_DSN = env("SENTRY_DSN", default="")
if SENTRY_DSN:
    from apps.core.sentry import init_sentry

    init_sentry(
        dsn=SENTRY_DSN,
        environment=env("SENTRY_ENVIRONMENT", default="development" if DEBUG else "production"),
        release=env("APP_VERSION", default=None),
        traces_sample_rate=env.float("SENTRY_TRACES_SAMPLE_RATE", default=0.0),
    )
