# Generated by Django 5.2.17 on 2026-10-01 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cinema',
            field=models.ForeignKey(blank=True, help_text='Rạp mà nhân viên phụ trách (chỉ có ý nghĩa với role staff).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='cinemas.cinema'),
        ),
    ]
