# Generated by Django 5.2.17 on 2026-10-01 13:35

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='combo_price_positive')],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('discount_type', models.CharField(choices=[('percent', 'Phần trăm'), ('fixed', 'Số tiền cố định')], max_length=10)),
                ('value', models.PositiveIntegerField(help_text='Phần trăm (1-100) hoặc số tiền VND, tùy loại.')),
                ('max_discount', models.PositiveIntegerField(blank=True, help_text='Mức giảm tối đa (chỉ cho loại phần trăm).', null=True)),
                ('min_order_amount', models.PositiveIntegerField(default=0)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Tổng số lượt dùng. Để trống = không giới hạn.', null=True)),
                ('per_user_limit', models.PositiveSmallIntegerField(default=1)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('code', django.db.models.functions.text.Upper('code'))), name='voucher_code_uppercase'), models.CheckConstraint(condition=models.Q(('value__gte', 1), models.Q(('discount_type', 'fixed'), ('value__lte', 100), _connector='OR')), name='voucher_value_range'), models.CheckConstraint(condition=models.Q(('valid_from__isnull', True), ('valid_until__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='voucher_valid_window')],
            },
        ),
    ]
