# Generated by Django 5.2.17 on 2026-09-30 04:45

from django.contrib.postgres.operations import BtreeGistExtension
import apps.showtimes.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinemas', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(editable=False)),
                ('price_standard', models.PositiveIntegerField()),
                ('price_vip', models.PositiveIntegerField()),
                ('price_couple', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='showtimes', to='movies.movie')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='showtimes', to='cinemas.room')),
            ],
            options={
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['start_time'], name='showtimes_s_start_t_2f568a_idx'), models.Index(fields=['movie', 'start_time'], name='showtimes_s_movie_i_274781_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='showtime_end_after_start'), django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('is_active', True)), expressions=[(apps.showtimes.models.TsTzRange('start_time', 'end_time', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&'), ('room', '=')], name='showtime_no_overlap_in_room')],
            },
        ),
    ]
