# Generated by Django 5.2.17 on 2026-09-30 09:12

import apps.payments.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mock', 'Mock gateway'), ('vnpay', 'VNPay')], default='mock', max_length=20)),
                ('txn_ref', models.CharField(default=apps.payments.models.new_txn_ref, editable=False, max_length=32, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('succeeded', 'Thành công'), ('failed', 'Thất bại'), ('needs_review', 'Cần xử lý thủ công')], default='pending', max_length=20)),
                ('gateway_txn_id', models.CharField(blank=True, max_length=64)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bookings.booking')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('booking',), name='one_pending_payment_per_booking'), models.UniqueConstraint(condition=models.Q(('status', 'succeeded')), fields=('booking',), name='one_succeeded_payment_per_booking')],
            },
        ),
    ]
