# Generated by Django 5.2.17 on 2026-10-01 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_checked_in_at_booking_checked_in_by_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'paid_at'], name='payments_pa_status_bed4b8_idx'),
        ),
    ]
