# Generated by Django 5.2.17 on 2026-09-30 04:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('synopsis', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('release_date', models.DateField()),
                ('poster_url', models.URLField(blank=True)),
                ('trailer_url', models.URLField(blank=True)),
                ('age_rating', models.CharField(choices=[('P', 'P - Mọi lứa tuổi'), ('K', 'K - Dưới 13 tuổi (có người giám hộ)'), ('T13', 'T13 - 13+'), ('T16', 'T16 - 16+'), ('T18', 'T18 - 18+')], default='P', max_length=5)),
                ('status', models.CharField(choices=[('coming_soon', 'Sắp chiếu'), ('now_showing', 'Đang chiếu'), ('ended', 'Ngừng chiếu')], default='coming_soon', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='movies.genre')),
            ],
            options={
                'ordering': ['-release_date', 'title'],
                'indexes': [models.Index(fields=['status', 'release_date'], name='movies_movi_status_66fc0c_idx')],
            },
        ),
    ]
